"""initial_schema

Revision ID: 2b70d6e343f4
Revises: 
Create Date: 2026-03-22 20:26:03.513021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b70d6e343f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_rent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.Date(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('property_name', sa.String(length=200), nullable=False),
    sa.Column('brokerage_fee', sa.Integer(), nullable=False),
    sa.Column('ad_fee', sa.Integer(), nullable=False),
    sa.Column('payment_fee', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('is_white_flow', sa.Boolean(), nullable=False),
    sa.Column('fee_calculation', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.Date(), nullable=True),
    sa.Column('is_delivery_flow', sa.Boolean(), nullable=False),
    sa.Column('ad_calculation', sa.Integer(), nullable=False),
    sa.Column('total_summary', sa.Integer(), nullable=False),
    sa.Column('status_flag', sa.String(length=50), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('closing_month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_rent')
    op.drop_table('employees')
    op.drop_table('stores')
    # ### end Alembic commands ###
